#!/bin/sh
set -eu

SQL_DB_NAME="${SQL_DB_NAME:-olfit_db}"
SQL_TEST_DB_NAME="${SQL_TEST_DB_NAME:-test_olfit_db}"
SQL_DB_USER="${SQL_DB_USER:-olfit_admin}"
SQL_DB_PASSWORD="${SQL_DB_PASSWORD:-olfit_password}"

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<EOSQL
CREATE DATABASE IF NOT EXISTS \`${SQL_DB_NAME}\`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

CREATE DATABASE IF NOT EXISTS \`${SQL_TEST_DB_NAME}\`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

CREATE USER IF NOT EXISTS '${SQL_DB_USER}'@'%'
  IDENTIFIED WITH mysql_native_password BY '${SQL_DB_PASSWORD}';

ALTER USER '${SQL_DB_USER}'@'%'
  IDENTIFIED WITH mysql_native_password BY '${SQL_DB_PASSWORD}';

GRANT ALL PRIVILEGES ON \`${SQL_DB_NAME}\`.* TO '${SQL_DB_USER}'@'%';
GRANT ALL PRIVILEGES ON \`${SQL_TEST_DB_NAME}\`.* TO '${SQL_DB_USER}'@'%';

FLUSH PRIVILEGES;
EOSQL
